### ISSUE TITLE
Change Hidden Levels maze wall color from white

### ISSUE THREAD

**Issue by jerkyspace** [jessaskey/mhavocpe#107]
Maybe the Hidden levels maze walls should be the normal green or yellow/amber since they are located in the L1-20 zone prior to the Mainframe Cube. 

I think it is picking up the white walls from the mainframe sections because they are located in the Level 25-28 slot right after it.

If possible maybe do a slightly different type of Starbase when you land as well or at least the normal type found on L1-20 (again shows the cube because they are in the L25-28 slot).

**Comment by jessaskey** [comment]
I will check this out, I think you are correct, the hidden levels should be Green maze walls. 

On the different bases, it is sorta vector ROM intensive to make a whole new set of 'shapes' because the shape has to be drawn several times... Tact Scan Center, Tact Scan Upper Right, While fighting in space and then during landing. So it has to exist 4 times for each shape, that is a big reason why the regular 4 shapes are repeated. I will keep this open tho in case we have extra vector ROM space to do some 'fun' modifications on them.

**Comment by jessaskey** [comment]
I think that what Im going to do on this and I will try and get it put into Release v0.58 is cycle the colors of the walls in a special way on the Hidden Levels... this will make them unique. Since each of the 'Tesseracts' has a special color associated with it (and used in the 'token/badge' for that tesseract: Blue,Purple,Red,Orange) Im going to do the wall color special for each one, then they will have a common color tone.
