### ISSUE TITLE
Self Test number of lives selection not taking properly above 6 lives

### ISSUE THREAD

**Issue by jerkyspace** [jessaskey/mhavocpe#108]
In the new romset 0.51 I just noticed that when you try to change the number of lives in Self Test it gives you a different value than you selected for certain values (sort of like the Demo Mode>Hard Diff bug). 

I tried to set it up to Demo Mode with 9 lives but after confirming it said 6 lives instead. I tired selecting other values and they seemed to come back predictable results : Selecting 8 lives ends up as 3. 7 gets you 4. But everything else is fine from 6 lives to 0 after that. 

Weird.

**Comment by jessaskey** [comment]
Okay, I see the issue here... the way the DIPS are defined in HAVOC is that there are only 4 options for bonus lives. They different based upon the coin mode. Because of that, I am stuck with only 4 bonus live options... Im going to make it use the 3,4,5,6 range for now and I will get it fixed in the 0.52 release.

Later down the road, Im going to redefine all the DIPS for mhavocpe and give 3 DIP switches for Bonus Lives (9 options.. probably 1-9). 

![image](https://user-images.githubusercontent.com/3683098/62994925-9c77c480-be1b-11e9-8581-83b4c8480d4a.png)
