### ISSUE TITLE
Reactors move around slightly sometimes

### ISSUE THREAD

**Issue by jerkyspace** [jessaskey/mhavocpe#122]
When you get close to a reactor it doesn't stay in place sometimes as you move near and or past it. It does a little "dance" around it's original location and doesn't stay locked in place like other objects all the time. It's more noticeable with the increased size MegaReactoid on level 24.

**Comment by jerkyspace** [comment]
This issue may be why all reactors in Rev 3 were drawn slightly off the floor. When you draw them up against it they tend to "dance" down below the floor level due to this bug that only seems to affect reactors. All other objects are locked on the map.

**Comment by jessaskey** [comment]
I will look into this, I think this is actually normal but on a vector monitor, it doesn't do this... just on MAME. But I will investigate.

**Comment by MajorHavoc** [comment]
That could happen on a vector screen if there is too much drawing without a center command before the reactor is drawn. I do not know how MAME emulates the vector generator, but to do it "correctly" they would have to accumulate positions so the next draw (before a center command) is relative to the previous position, +/- some drift over time.  It seems strange that it moves. I blame MAME too, since typically that object would be positioned after a center command, and uses the scroll values to know where to draw. 

Jess, is it possible that the code does not update the reactor position correctly when scrolling?

**Comment by jessaskey** [comment]
To Owen's point, I don't see anything in the positioning code that looks funny around this and in fact, the reactor position is set by the same 'locate' function that all other non motion objects use, so this may indeed be something with the digital part of MAME perhaps. Im going to mark this one closed for now unless it comes up again for some reason.
