### ISSUE TITLE
Game crashes hard when jumping and pushing the shield button

### ISSUE THREAD

**Issue by bakerhillpins** [jessaskey/mhavocpe#128]
MHEditor v1.2.1064.0
HBMAME v0.207

So this is what I have to do to reproduce this. I don't know if it's all required or not but I got it to happen 3x doing this.

Open editor,
Load levels from PE ROM image shipped with editor
Play Level 6, goal is to get token between 2 ion cannons in maze.
Start by going left. I typically jump and shield at the same time. Shield kills pyroid and then Rex runs into Perkoid at upper hallway and dies. I typically hold the shield button down and don't let it up until after Rex dies.
Next life, go left, up to top then drop down and go right to slip into the open space below and to the left of the 1st IonCannon. Wait up against the wall just below the cannon so that you can jump over the cannon and the shot from the cannon off the screen. 
When you jump up to go over the cannon and the shot start quickly mashing on the shield button. Typically it will crash at this point.

It goes NUTS. Like screen flashing and all sorts of weird noises. It appears to keep playing in the background though because sometimes I can hear Rex die and the other sounds mixed in to the nonsense. 

Mashing on escape for 5-10 seconds seems to get me to exit HBMAME but when I do my display settings have been changed to "Portrait (flipped)" which ultra sucks because the mouse is inverted and it's hard to do anything.

**Comment by jessaskey** [comment]
Okay, thanks for all the info... I will look at this tonight!
________________________________

**Comment by bakerhillpins** [comment]
So I was thinking about this and I wonder if it's got to do with the interaction of hit test code and the new token fade in/out stuff. Jumping back and forth between the regular hit testing for just Rex and Rex with Shield.

**Comment by jessaskey** [comment]
Bryan, I just tried to do this a few times tonight and was not able to re-create this. Jerky made getting to the tesseract from the left 'highly discouraged' so you have to get it on the way out from the right side and he made it substantially easier too by removing the second Ion Cannon and the second Pyroid down by the Escape pod. I like the feel of this level now (for level 6) because there is now a 3 layer choice for the player... normal escape, miss pod and tesser.... escape pod only exit, miss tesser and then pod exit + tesser... so it makes this level super interesting and also not overly difficult. 

Either way, there may be have other circumstances that may have fixed this, but if you have the rhythm on it, maybe you can try again (even from the left if you want, just kill the fast pyroid with your first Rex maybe).

**Comment by bakerhillpins** [comment]
I'm going to try to move back to that release and reproduce it first. Then move to the new stuff and see if anything changed. In the long run it might be easier to move back to that release and debug it there even though it's way old at this point. 

I'll let you know what I find.

**Comment by jessaskey** [comment]
Okay, Bryan and I sat down and figure out that this was a specific issue with his PC and MAME/HBMAME. It seems that for Intel Graphics chipsets, that a common hotkey combination is CTRL+ALT+ARROWKEY and in Major Havoc, CTRL = Shield and ALT = JUMP and the arrows are the whirlygig. So if you shield and jump at the same time while attempting to move, then this will cause Windows 10 to rotate the screen. Henceforth, that seems to upset MAME/HBMAME quite a bit with really weird screen flashing and oddities while the game still attempts to run in the background. Case closed on this caper!!
