### ISSUE TITLE
VAXX Bonus is skipped if the player dies in maze

### ISSUE THREAD

**Issue by jessaskey** [jessaskey/mhavocpe#135]
The final VAXX bonus is supposed to countup after the final space station level and is also supposed to give a different 'destroyed station' bonus depending on if the player escaped the station after triggering the reactor or if they died on the way out. Unfortunately, right now, if the player dies.. the game does not pick back up and do the Vaxx bonus, homeworld animation and end story... it just goes to the next level. This needs fixed.

**Comment by jessaskey** [comment]
I talked to Owen about this... his preference is that if a player dies between setting off the reactor and escaping the final maze, that the player should start over again on the final maze (if they have lives left)... If they die trying, then the game should only allow them to continue one level back like most other levels... so if they die on Level 21 and game over, then they can only continue on Level 20. If they die on Level 21 (supa station) after setting off the reactor and have lives left, then they will start all over on entering the maze for Level 21 again!  We will call this the Groundhog Day Maneuver.

**Comment by MajorHavoc** [comment]
I totally misunderstood you. Sets off final reactor and dies leaving the final facility - game ends! You get credit for destroying the factory just like on ships, but no bonus. And there is no next level anyway. And your people can now escape, and the final is a celebration anyway, maybe just a little less for all of your people who died in the factory. After all, clones are free, were giving them away. And, no bonus for blowing up the planet factory if you did not escape. I’m wondering if the escape pod should make an appearance here?

I really thought you were asking what happens if he dies before setting off the final reactor. Sorry for my confusion. Good thing I occasionally look at your notes on Guthub. :-)

-Owen-

**Comment by MajorHavoc** [comment]
Yes. See my other message for me just being an idiot. I answered for the wrong scenario. Doh.

**Comment by jessaskey** [comment]
Nahh, you are good… there are lots of things flying around for sure in all these emails etc.. I will put in a fix for this one in the next ROM set (this weekend)… then it should follow your script!
