### ISSUE TITLE
Player walking into MegaReactoid

### ISSUE THREAD

**Issue by jerkyspace** [jessaskey/mhavocpe#146]
0.58 romset
Editor 1.2.1064.0
HBMAME 0.209

I just noticed that while DeHand correctly pushes just the mega reactor button on Level 24, the player walks into the middle of it before it is set off. 

Seems like the collision detection is off maybe related to the size scale up (which is growing on me lol). The player should just bump into the button on the outside without passing through like the smaller reactors.

**Comment by jessaskey** [comment]
I just fixed the code for this for the 0.66 release. I had to do quite a few changes for the Mega-Reactor...

1. Adjusted X distance to contact reactor as Jerky points out in the issue.
2. Since the mega-reactor is two stamps tall, had to modify the collision routine so Rex would still contact the reactor when in the stamp above, also the rtcol flag has to be set so Rex can't move past the reactor  when in the stamp above.
3. Changed the 'locate' routine which determines if the object is on screen and should be drawn. The mega-reactor was dissapearing from the screen completely when the bottom of it actually only went off screen.
