### ISSUE TITLE
Adaptive difficulty type behavior on "Galaga" space station battle.

### ISSUE THREAD

**Issue by bakerhillpins** [jessaskey/mhavocpe#169]
This is a hard one to prove at the moment, I'll need to take some video. It seems like every time I die battling the spaceships trying to land for level 6, when I start battling the ships again they are way more aggressive than they were on the previous life.

**Comment by jessaskey** [comment]
Okay, so I looked at the code for the Fighters (Type B levels) and the Fighters+RedBar (Type D levels)... and there are only two things that vary as far as gameplay and difficulty...  the number of fighter shots that can be on the screen at the same time (from 2-8) and then the fighter shot X tracking velocity (from 6-25 units per move). 

One thing to keep in mind that both the space section AND the maze section, that the fewer number of objects on the screen, the faster things can move...  so like in the mazes, level 5 is the best example of that... the only reason that whole level is so 'fast' is that there are hardly any enemies (and none that move outside of trip pad fireballs). The space sections are the same... so I think that if you die, when the level restarts, it starts kicking out the ships again from scratch, so they will actually be a tad faster until more ships are ejected from the space station. I stepped through the code and both the X shot tracking AND the enemy shot count DO stay the same on space levels even after you die. So, I don't think anything is actually getting more difficult, I think it may be the factor above if anything.

Also, I sorta audited the values of the two settings above and found that the difficulty was ramping up pretty fast so that the space fighters were pretty close to max difficulty by Level 13... So, I skewed the difficulty so that the difficulty ramped up to max over the full span of the 21 levels... that should make it overall a little more linear increase to the homeworld.

**Comment by bakerhillpins** [comment]
That explanation makes a lot of sense and follows my observations. Specifically, when I think about how fast the shots were when there were 1-2 fighters left on the screen.

Any way to "pace" the drawing routine to give a more consistent timing/frame rate and feeling of speed? It sounds like the code responds to the completion of the vector generator rather than say a periodic interrupt? I realize I'm naive with respect to the overall structure of the code and I know that in upper levels it's running as fast as it can.  Typing that out I'm hearing that's far from a simple detail to change. Also... the way level 5 responds faster is kinda cool in that it switches it up in the game.

**Comment by jessaskey** [comment]
Ha... no not at this point. Owen could probably go into this more, but at this point in code, there didn't seem to be any idea of 'throttling' based upon the speed of the main loop it was basically in the mode of running as fast as it can. The IRQ would be the way to base any sort of measurement of main loops against time but I think that in the end, the complexity of the Maze rendering sorta made it so that any sort of throttling would A)not really gain much, the 'sliding' isn't that annoying  B)would only slow down the mazes more where it was running full crunch because of the added code introduced for throttling.

**Comment by jessaskey** [comment]
Im going to close this version of this bug for the version .79 release but if this is still an issue, it can be resubmitted as an issue and I will reference this one.
