### ISSUE TITLE
Vector drawing error, Level 3, exit transporter.

### ISSUE THREAD

**Issue by bakerhillpins** [jessaskey/mhavocpe#172]
When exiting the maze on Level 3, you go through the transporter. When you materialize a vector shoots off to the upper left. See pic.

![image](https://user-images.githubusercontent.com/5980709/166150045-c14ec459-9e69-46da-ae9e-f37faa8e19a0.png)

**Comment by jessaskey** [comment]
I have seen this (on MAME even) but been unable to get it consistently to happen... I *think* that whatever is causing it will happen on any transporter level because Jerky has reported this in the later levels... but it does happen on level 3 which is substantially easier to get to repeatedly. I though maybe it didn't happen unless you played previous levels vs using DEMO mode to start right on Level 3 but I have tried both approaches and not been able to get it happen. If I can find a way to repeatedly get it to happen, it will be substantially easier to find the issue rather than just reviewing the code, but we will see what we can do. I will need to capture it in MAME and then do an analysis of the VGRAM content to see where it is being drawn, clearly on the transporter sparkles tho... I suspect it is a VGROM paging issue perhaps related to what else is on the screen when the transporter is drawing the sparkles.

**Comment by bakerhillpins** [comment]
I've attempted to reproduce this a few times last night and no dice. I didn't play competitively on that level though, just raced through to see if it would show the bug. I also kept going back and forth through it to see if it would eventually occur. Nope.

I'll play a few competitive games this afternoon and see what if anything changes.

**Comment by jessaskey** [comment]
So there is a distinct chance that the waste vectors were causing this too.... so Im wondering if removing the waste vectors, if we solved this as well? I have not seen this since before the 'blr' ROM set.

**Comment by jessaskey** [comment]
Okay, I spent *alot* of time and tracked this down... here is a picture..

![image](https://user-images.githubusercontent.com/3683098/166831606-6d939f73-1338-4087-a97a-d1b24cb4c82e.png)

Looks like after doing a VGRAM dump and running it through my simple 'viewer tool' (scale is not quite right in some places, but it solves my issue)... 

![image](https://user-images.githubusercontent.com/3683098/166832294-ddfc0aee-4472-4932-bbdd-73c6acbbab8d.png)

**Comment by jessaskey** [comment]
Okay, I found and fixed this... should be good to go in v0.80.... issue was not restoring the X register properly after calling a new subroutine.
