### ISSUE TITLE
The Alpha CPU Self Test page flickers.

### ISSUE THREAD

**Issue by bakerhillpins** [jessaskey/mhavocpe#178]
The Alpha CPU Self Test page flickers, much more so than any of the other test pages. It does have a LOT of text so it may just be the nature of the beast but I figured I'd mention it anyway.  It also seems to stop drawing the outer red box as it draws it from Left to Right across the top of the screen.  Meaning the left hand side of the top of the box is red, and about 60% of the way across the top the red fades away like it's slowly turning off. I don't see this on other screens.

**Comment by jessaskey** [comment]
Yep, this is a direct symptom of 'too many vectors'... similar to what you see on the Star Wars credit screen. Ironically, writing small text is the true killer because of all the vectors in a letter with lots of invisible vectors for positioning too. I will double check on my hardware about the top red line to see what I can tell before I close this issue tho.

**Comment by bakerhillpins** [comment]
So I just went downstairs to grab a pic of this and it didn't happen (the red line fading out) so I'll have to keep track of this during my other testing. I knew I should have grabbed a snap of it when I saw it.
