### ISSUE TITLE
Killing the last flyboid with the Catastrofighter on Level 2 causes random vectors to be drawn on the screen.

### ISSUE THREAD

**Issue by bakerhillpins** [jessaskey/mhavocpe#183]
Playing the space battle to level 2, I destroyed the last Flyboid by hitting it with the Catstrofighter. The result is a quick flash of what appears to be random vectors on the screen. Almost looked like they were drawn in sparkle.  The subsequent Landing sequence seemed normal as did game play.

**Comment by jessaskey** [comment]
I tried to duplicate this one and was not able to do it... it was actually fairly difficult to die by hitting an actual ship rather than one of their shots. I will leave this open and hopefully we can collect more info here if it can be duplicated again. There is a small chance that this bug gets fixed by some of the other fixes in this release but that is also a bit of wishful thinking on my part as this will be pretty difficult to track down unless we can find a way to consistently get it to happen.

**Comment by bakerhillpins** [comment]
When 0.81 comes out I'll give this another shot at reproducing and maybe try to grab a video.

**Comment by bakerhillpins** [comment]
I've been able to try this a few times and I've not seen the artifact that I saw previously. I'll keep trying and report back.
