### ISSUE TITLE
Music varies speed/pitch (or whatever it's called)

### ISSUE THREAD

**Issue by bakerhillpins** [jessaskey/mhavocpe#198]
I'll start off with this may be just the way it is because of the game architecture.. However:

I can notice the music becoming faster as more and more "enemies" are removed from the level. An easy way to hear this is to play the 1st token level on 0.85 PE.  There's only one Maxbot and all the rest is O2.  At the end (when you've consumed the all the O2 you can hear the music speed up.

I'll try to grab a video.

**Comment by jessaskey** [comment]
Since you mention a Maxbot specifically, there is a background sound associated with the Max robot and the speed of it's 'we-ew we-ew' sound *does* increase as Max gets closer to Rex. As Rex moves away from Max, the sound should decrease in pitch. Now, what Im curious about is that you are talking specifically about a different sound (enter/exit music?) or are you indeed talking about the Max sound itself?

**Comment by bakerhillpins** [comment]
I was talking about the background sounds/music..  not the max sound. I'll try to reproduce this in a video.
