### ISSUE TITLE
Alpha Tesseract returns to Level 1 not 7

### ISSUE THREAD

**Issue by bakerhillpins** [jessaskey/mhavocpe#209]
0.86 PE in Free Play.

Picked up Alpha Tesseract on level 6.  Warped to 1st hidden level and completed it. Game returned to Level 1, not 7 as it should have.

As it turns out, This is a bug in Jerky's mazes...  It seems all of his Tesseracts have Level 1 set as the return level. I think we need to make this Automatically filled in via the Editor...

**Comment by bakerhillpins** [comment]
![image](https://user-images.githubusercontent.com/5980709/179870494-46051489-35bb-4ef1-88b2-d9c683d6a316.png)

**Comment by bakerhillpins** [comment]
I'd like to talk with you about how to solve this... I think we should make the field non-editable in the editor and when mazes are saved as a collection the "ReturnLevel" value will be automatically set to the current level + 1;

Otherwise this is going to be a problem forever because it's a prime candidate for being overlooked.  I'm relatively sure that you and Jerky are not validating the maze collections before they are published/serialized into ROMs.  Even if you were this would be missed because there isn't a validation rule to test this.

Oddly, this could be a cool feature but it's also one that could be exploited for huge points. I could continuously loop from 6 to 1 and rack up the points.  This is because the Token "goes back in time" and I'd speculate that it's not removed from the maze the 2nd time around. Though it could be and this could be a feature... 

Anyway, we should probably make it return to the next level for CAX.

**Comment by jessaskey** [comment]
Yeah, well, to your last point first... I sorta did this because I was going to make a set of mazes where certain areas of certain mazes were only available if you somehow 'looped' back to a previous level in the game... but the clincher was that if you had the KeyPouch (imaging getting it in an early level in a difficult spot)....  then in another level, you might be able to go get a a key that might be in a difficult spot and keep in from level to level (this is what the keypouch does)... and then after the 'time loop'... you might have a key that you would not ordinarily have and you might be able to do different things in a level etc.. you couldn't loop forever necessarily because that key would be 'used' potentially. Anyway, that was my idea for doing it, but Jerky chose not to go down that path (which is good by me for sure).

So, yeah, for now... on the F10, we can just default it to to be the level that is is being designed on.

**Comment by bakerhillpins** [comment]
Ah, yes. I remember that now.  It's a great option, just need to find a way to make sure folks think about the consequences. 

There are several ways to deal with this in the editor. Another would be a dialog box that pops up and asks the user for the return to level when it's added to the maze.  So at least it pushes it in front of them. 

Still think that defaulting to the current maze +1 and adding a warning validation via the editor is the best option.. then noobs don't make mistakes and advanced users can change it to mix it up.

**Comment by jessaskey** [comment]
You know.... I looked at the code to 'fix' this on the F10 export and it is actually going to be more difficult than I thought. 

SO... Im going to actually fix the return level values in the current two collections and email these out to Jerky so hopefully he starts using that as his basis... I think that at some point, the editor must have had a bug that somehow didn't load these values properly or something so they got set to 1 and then were orphaned with bad values.

**Comment by bakerhillpins** [comment]
Looks like (from external email traffic) that Jerky updated/fixed his maze designs and you've seen them so that's means he's using fixed stuff and so are you! 

I was thinking about his "feature" again and wanted to get down in writing that if going back in time is something we support, then we will need to track the max level obtained. At the moment when someone continues we just allow them to get to the level they were at. Which in my case with this issue meant that I could only continue and restart at level 1 (since that's where I lost my last man), even though I made it to 6.

**Comment by bakerhillpins** [comment]
This appears to be fixed in 0.87 PE

I was able to test the 1st Tesseract (alpha) on level 6. It returns to 7 properly. I freaking missed the 2nd tesseract as I'm a complete tool.  DOH!
