### ISSUE TITLE
Transporter at bottom of Level 21 causes reset.

### ISSUE THREAD

**Issue by bakerhillpins** [jessaskey/mhavocpe#211]
0.86 PE  Demo Mode

Start on level 21. Enter the grey transporter at the bottom of the maze and the game will reset.

**Comment by jessaskey** [comment]
Okay, this is fixed... the issue was introduced in 0.86 by me trying to do the fancy 'key stashing' on Level 21 which would allow the player to start back on level 21 with the keys they originally had when the left the level via the transporter. After discussing with Bryan, we both didn't like that the player had to recollect their keys for Level 21 if they died on any part of the final station, however, it really does make the final level worthy of the 'final boss' so, I took out all my key stashing code anyway.
