### ISSUE TITLE
Rex jumps off the top of the maze if you run out of 02 while jumping.

### ISSUE THREAD

**Issue by bakerhillpins** [jessaskey/mhavocpe#216]
I did this on the 1st maze. Jump when you're about to run out of O2. You will die of course. Then when your next man starts the jump appears to still be active and Rex jumps over the maze entrance and out into space.

**Comment by jessaskey** [comment]
I have not been able to reproduce this, at least on Maze #1. I died jumping straight up by running out of oxygen. I did this right at the entrance to the right where I have 2 square of distance so I had to run out of O2 right in a quick jump. I did notice that even in death, the jump button seems to be 'active' while doing the dying animation because the maze seems to move like Im jumping again during the death animation. So maybe you were doing this during one of the longer vertical jumps on the sides or something? I haven't been able to duplicate it over there either tho.

**Comment by bakerhillpins** [comment]
I played to level 6, got the Tesseract, and died jumping up the long elevator shaft on the right hand side of the maze. I held the button down the entire time. 

I'll have to try it again.

**Comment by bakerhillpins** [comment]
Just reproduced it. Make sure that you are both jumping and moving to the left in the shaft when you die.

**Comment by jessaskey** [comment]
Okay, I see the effect, it just doesn't get you out of the maze on Level 1... but I can see how it throws you more to the left. I just put in some code that should solve this so I will get you this TEST set of 1.01 ROM's so you can verify if you want.

**Comment by bakerhillpins** [comment]
Test ROMs would be good. Though if you could tell me which ROM changed so I don't have to burn the set.

**Comment by jessaskey** [comment]
Unfortunately, the code change was in the main page (bottom half even)…. Which means that every pointer to code in Main ROM (holistic) shifted up by 4 bytes… so that pretty much invalidates ALL 4 of the Alpha ROM’s… BUT, upside is you don’t have to reburn the VECTOR or GAMMA ROMs… you *will* get self test errors just FYI (not that that matters) because the ROM’s are a different version (1.00 vs 1.01 BETA) and the game expects ALL ROMs to be the same version otherwise it will tell ya!

So, all in all, only reburn the 4 Alpha ROMs when I get this set to you tonight!

**Comment by bakerhillpins** [comment]
This is fixed in 1.01 beta. 

I do see how this could be a cool Easter egg sort of thing.

**Comment by bakerhillpins** [comment]
FYI, I saw this again on the last romset you sent which was a "debug" build so not sure if it had or didn't have these changes. I can't reproduce it however. Tried several times.

Happened after completing the space battle and landing on the space station. I wonder if the entry point in this case is missing the code you previously added to catch the case of dying in the maze
