### ISSUE TITLE
Data in stats page is in Hex?

### ISSUE THREAD

**Issue by bakerhillpins** [jessaskey/mhavocpe#225]
If you look at the included image XLives seems to be Hex rather than decimal. Not sure if it's just this value or not.

![image](https://user-images.githubusercontent.com/5980709/210149621-8efe9b7f-3281-4c6b-9e6e-7c7ae0ccd1e0.png)

**Comment by jessaskey** [comment]
I set decimal mode before the addition of these stats, so they will fix themselves and work properly now.

**Comment by jessaskey** [comment]
...and just to clarify here because I think we talked about this in Texts..... if you have hex data showing now... it will only update next time that specific counter gets added too.... so for the 3A example above, that would not change until another xlive was earned and then it would flip to 40.  If a warp count was at a hex number, then that specific warp would need to be attained before that number increased, specifically none of the others would necessarily change. 

The root issue was that decimal mode was not set on these counters when adding new values.

**Comment by bakerhillpins** [comment]
Yes, expected the screen to be updated when I got new data. Unfortunately when I did play a game and get a extra life and a tesserract to a secret level the EEPROM now flags errors and all [stats are zero](https://github.com/jessaskey/mhavocpe/issues/208#issuecomment-1373734338):
