### ISSUE TITLE
Space Station starts in lower left hand corner

### ISSUE THREAD

**Issue by bakerhillpins** [jessaskey/mhavocpe#228]
Demo Mode,

Select secret level 26 (2nd secret level) and note that the space station will start down in the lower right hand corner of the screen. It immediately zooms to the top and there really isn't anything that goes wrong here, but it's the only level that does this of the 4 secret mazes.  

I wonder if it's because that's how all "B" style space stations start?  I'll have to try that out.

**Comment by jessaskey** [comment]
I think this might be a side effect of starting a first game in demo right on Level 26 or something.... When I play in MAME, my space station starts in the lower left corner for some reason. Looking at the code tho... the issue seems to be that the space levels with fighters (B and D mazes) do have a full 'init' process. they sorta just start with the data that was present in the station X and Y locations... I put in some code to always init the Y position back farthest away now, so the instant 'oh shit' moment is gone. Iroically tho... because the station was so close before.. the two red bars slung off to the side really fast and always missed the player... now that it is far back, those first 2 red bars you really got to get swinging early otherwise there is a low chance you are going to get away from them at the speeds in the XX/hidden levels!!

**Comment by bakerhillpins** [comment]
Weird, it's the only level that does this though? And it doesn't matter if I start on that level or not. If I start on 25 and play through to 26 it still does it.

**Comment by jessaskey** [comment]
So, there is some inconsistency in how the code deals with the 4 hidden levels.... they are all 'style b' mazes with the fighter space wave in Jerky's mazes, but really only Level 26 is natively a 'style b' maze. Since I gave the option of making the hidden levels any style (a,b,c,d) in the editor, there is a bit of some hack code around loading up space init values for Levels 25, 27 and 28... this is what is causing the issue. Is this inconsistent, yes, will I fix it?... not sure yet... what I don't want to do is add more bugs at this point, so it may stay like this. I will look at the code if I can get all the other bugs out of the way first!
