### ISSUE TITLE
If the Hint Text is longer than 42 chars it displays wrong.

### ISSUE THREAD

**Issue by bakerhillpins** [jessaskey/mhavocpe#238]
1.01
I loaded up jerky's MHPE 13790 04282023 Promised End mazes and changed Hint 2 text on Level 1 to the following:

"FOLLOW ARROWS, TOUCH REACTOID, EXIT BEFORE TIMEOUT"

When I play the level in HB MAME it displays as shown below:
![0000](https://github.com/jessaskey/mhavocpe/assets/5980709/7bf28466-8a86-4d00-8640-3e7df832e385)

Any character beyond the following string results in the incorrect display.
"FOLLOW ARROWS, TOUCH REACTOID, EXIT BEFORE"

Currently the code is setup to limit users to 50 character strings. Apparently anything over 42 chars in the string causes the error.

**Comment by bakerhillpins** [comment]
I just checked the latest PE mazes and the longest string in there is 41 chars.  The TE mazes appear to have shorter lengths.

**Comment by jessaskey** [comment]
Aren't there two hint lines in the editor?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jessaskey** [comment]
I deleted that last comment because I was replying on my phone and it sent before I finished... Yeah, I think that both HINT 1 and HINT2 need to be less than a certain length... I thought it was gonna be more like 40 but obvs if there are longer ones that display correctly, then that is the max... it is probably due to the macros that do the 'centering math' because Im basically looking at the length and then doing some calculations and defining the start position of the text all based upon the length. Can we just change the limit in the editor to be 41 characters since we know that works properly?

**Comment by bakerhillpins** [comment]
Yea, changing the editor is fine. We circled around a limit a bunch in the past but that's the easiest. 42 is what works so I'll use that, Anymore than that displays wonky do to the centering algo.

**Comment by jessaskey** [comment]
Just to document things a little for posterity... here is the code in assembly that 'centers' text.. The CZMESS macro is what calculates everything... that special parameter in the 3rd position is a 'hidden' variable that I put into the assembler for any .ctext directives in the TASMX executable..... the 'mzh03a_', when the assembler sees a .ctext it will define a variable with a trailing underscore that defines the length of that string.... 40 in this case.

mzh03a  .ctext "USE SHIELDS TO DESTROY 1 ROBOT OR PYROID"
        czmess(mzh03a,$50,mzh03a_)


the macro definition for czmess is

![image](https://github.com/jessaskey/mhavocpe/assets/3683098/966e49f0-a063-4f4b-8f85-a0e6beff85e9)

If you look at the first calculation there for the ___zmeslen you can see the limitation... basically since Im using a subroutine to render text with standard scaling factors, I can only position back left (negative) since the position vector is limited to being between 0 and -128.... the scaled position vector for text (to get finer positioning) is a factor of 3 smaller... so any value over 42.6 will cause and overflow and cause the text to the position 'positive/right'. So that is explicitly the reason why. So, we *have* to limit in the editor... I will have to see why it is overflowing and rendering badly because I have a text in the macro, it is just apparently wrong, looks like that should be .byte $FF actually. In the end, we will still want to limit the text length in the editor so that we can prevent folks from writing off the right edge of the screen AND keep it centered.

\___zmeslen .set (-1*((zlen)*3))

**Comment by jessaskey** [comment]
This is a limitation of the current code... will need to put a limit in the editor to prevent this or just make it well known that long text may break things! :-)
