### ISSUE TITLE
Watchdog makes game unplayable

### ISSUE THREAD

**Issue by Robbbert** [jessaskey/mhavocpe#35]
I've tried making this work in the current version of HBMAME, following on from your request https://github.com/mamedev/mame/pull/3474 .

However it watchdog-resets both in the attract mode and while playing the game, and is therefore unusable.

The same problem occurs with the version of MAME in your repository.

**Comment by jessaskey** [comment]
Yeah, strangely, Im having lots of issues getting my code merged into MAME properly due to a number of issues (mostly me be an SVN person and not a GIT person I think)..... either way, the big change is that the Alpha Processor ROM Page handler needs to be updated to use the new method

At this point my fork is so out of date (April 2018) that I can't compile it against the current build of MAME in the master branch anymore. 

I am using the version of MAME in my repository right now to test the ROM's so I know that version does work.... Let me look into it more this evening and help get you running on that at least.

I think probably just need to ditch my fork and my pull request and get these files updated and then just mail them to the mamedev email and see if someone will get them into the repository for me so I don't muck things up too much.

**Comment by Robbbert** [comment]
Still not working, even with your own version of MAME. When the ship drops down to land on the white platform, it suddenly expands then freezes. The watchdog then kicks in. Checking with the debugger reveals on exit of an interrupt it runs into the weeds before eventually ending at a KIL opcode.

It can't possibly be included in MAME until you sort that out.

Also, even though I followed your rom instructions to the letter, I have different CRC32's to what you've put into the PR.

**Comment by jessaskey** [comment]
I think we have a disconnect... please ignore PR 3474, that Pull Request and repo has issues. I have closed that PR and made a new PR 4361 - https://github.com/mamedev/mame/pull/4361 

The files in this new PR have the correct CRC files for the mhavocpex (CAX 2018 BETA version) ROM's which you can create from the patch files here in this repo.

Make sure you are using the mhavocpex driver as well.  You can email me directly at jess@askey.org if you want to walk through it, Im happy to help. LMK.

**Comment by jessaskey** [comment]
Im building another mame64.exe to upload here so you can test without source building it if you want. I will also verify that it plays okay and report back.

**Comment by jessaskey** [comment]
Okay, there is a new build of mame up in this repo... https://github.com/jessaskey/mhavocpe/blob/master/MAME/mhavocpex64.exe  This is a mhavoc only build to save space. I have tested it against the mhavocpex ROM's which can be built from this site (CAX 2018 release BETA)... and I was able to land on the maze and play in the maze fine. So Im thinking something is criss-crossed. Please let me know if you have more success. 

Additionally, I just updated the mame src files here if you want to try and build an hbmame exe again. 

thank you for the feedback!

**Comment by Robbbert** [comment]
Still no luck. With your new mhavopex64.exe it still resets. The problem must be with the roms, which do not match the crc's in your mame. I used mhavoc roms as input, since these are rev.3, but maybe you meant some other revision. I'll try other sets and see if the correct crc's can be obtained.

**Comment by Robbbert** [comment]
After further checks, only mhavoc roms are acceptable as input to patch_roms.bat. I ran it all over again, but the results are still the same. I used the bspatch.exe that you have here.

So, progress will not be possible unless the correct roms can be obtained.

**Comment by jessaskey** [comment]
Okay, let me go check out the patching again..... it was something I had to add at the last minute (rather than distributing full copyrighted ROM's)... so it has not been extensively tested.... You are correct tho.... the source ROM's are supposed to be mhavoc v3 ROM's. I will see if I can add a check to the source files to ensure they are also correct for the patch process.

**Comment by jessaskey** [comment]
I have verified that the patches can generate ROM's which are playable and match the CRC of what is in the PR #4361 . I did run into some interesting things making mhavocpex ROM's from the mhavoc ROM's on my Windows 10 machine... I wasn't able to get bspatch to actually output files with the version of bspatch which I had downloaded from here - https://www.romhacking.net/utilities/929/ . The only way I was able to build files was the run the bspatch exe from within a mingw environment.

At this point, everything should be very solid for you to test. Please let me know if you run into any issues.

Also, the new patches are indeed different than the original ones that I uploaded here, so you are correct that there was something wrong with them.

**Comment by jessaskey** [comment]
I should note, that the new ROM patches are indeed different than the original ones that were uploaded here, so you are correct that there was something wrong with them. thanks again.

**Comment by Robbbert** [comment]
The new psbatch.exe (24kb) included doesn't work, it doesn't produce any output file. Therefore I went back to the previous one (34kb) and this created the needed roms. The new roms matched what was needed and the game works in HBMAME.

The last time I spoke to the coordinator he was against adding this to MAME. This "might" change after CAX, i do not know. However the game will be fully supported in HBMAME, which still gives anyone the chance to play it. If you want other future revisions included please let me know.

Since the problem has been resolved, I will close this issue.
