### ISSUE TITLE
Make 1 new Music Background for Final Maze

### ISSUE THREAD

**Issue by jessaskey** [jessaskey/mhavocpe#44]
Make another Havoc sounding track for the final maze. I actually was watching Wargames the other day and the theme music when they show the WOPR computer is pretty cool, maybe something like that. :-)

**Comment by jessaskey** [comment]
Here is the track from the soundtrack.... starts at 33:26

https://www.discogs.com/composition/87fa2114-23d6-41d2-83ea-df4f29b1f396-Wargames

**Comment by jerkyspace** [comment]
I like the sounds linked below especially the initial creepy bass 
heavy thrumming and "computing" noises the WOPR is making before the 
movie horn stabs come in. Not sure if orchestra/horns are the right 
fit through for a game that has been all about the cold dead silence 
of space with only some creepy space station noises otherwise since 
level 1.
Just looping the initial computer sounds would make a great background 
soundtrack to the final mazes. The "computing" sounds minus the 
background bass thrum could start out as occasional blips here and 
there and increase as you progress maybe getting faster and faster. 
The thrumming background base could be linked to how close you are to 
the reactor (slower/faster/louder/softer).

I think this is a link to the scene from the movie using the same bit 
of music you point to in your email below :

WOPR Sounds
 https://youtu.be/_aUHQKneAdw

**Comment by jessaskey** [comment]
Yeah, just those low base tones, gonna work with them now that I have the RPM driver figured out to the level where I can actually translate musical notes into the data tables. **Thanks for the links, that was the exact scene I was talking about** 

I will post some stuff in this next version release (planned for next week... v0.22)

**Comment by jessaskey** [comment]
I may come back to this but I actually played around with making this on the Pokey, it sorta worked, but I don't have the time to get the correct envelopes for the different instruments required. I ended up taking the existing maze enter music and sorta turning it darker (more minor) and offbeat overtones, so it is sorta similar but more foreboding. If I have time near the end, I will work on making lots more music. I think particularly for the end story credits something like I,Robot by Alan Parsons Project would be cool.
