### ISSUE TITLE
Reactor invisible obstacle

### ISSUE THREAD

**Issue by jessaskey** [jessaskey/mhavocpe#54]
From Jerky:

I am still getting "stuck" on Reactors here and there like an invisible wall comes up to the right of them when you set them off. I feel like I should be able to move to the left and set off a reactor and then immediately dial away to the right. Instead I hit an invisible barrier I have to jump over/through. Very noticeable the new Level 13 Ion Think I Can (and Level 22 Space Dock see #7 below). I also noticed that in the original Rev 3 almost every single reactor is set up to the right of the player except for Level 11 which by no coincidence has the same issue I am seeing in new levels where the reactor is to the left of the player. Maybe this is a bug/feature the original had from the start?

**Comment by jessaskey** [comment]
I was looking into this and there is some code around the reactor that creates this invisible wall but it only does it on the center and right side... I actually feel like Rex should be able to move freely 'past' the reactor (but it causing the touch) just so there are no strange invisible walls. The Clock is similar in that it has an invisible wall, but it implements it from both sides and the only way to get past it is to jump over it (if there is space). For the 0.53 release, Im going to take off any motion stop for the Reactor so that you can evaluate the behavior and let me know which way you prefer on this one.

**Comment by jerkyspace** [comment]
0.53 romset

So the recent change that eliminates the "invisible" vertical barrier that is part of reactor objects does help the issues with it on levels 11 and 13...but I know why they put it in originally : it makes the object feel more "real" if you bump into it like you pressed the button to set it off (same for the clock).

It also keeps the player from flying through it and into the wall behind it which is in some cases a force-field that will kill them. The button is sort of arbitrary if you just pass right through it without the invisible barrier to run into. After some play testing I feel like we need the invisible barrier at the button to make it feel right. 

So I first reworked Level 11 so you set off the reactor from the left side to avoid the getting stuck issue on that level all together (since it was in the path of the player to get out and the button was on the opposite side of them). 

I did them same to Level 27 where it was easy to flip the transporter locations around to put the reactor facing the "normal" direction (button on left side where player approaches from).

Level 13 is not such an easy fix. I can't flip the level around so the reactor button is on the same side as the player approaches it because the maze is so small and the location of the entrance prevents this. I can't get the reactor facing the right way without a major design change to do so.

One solution might just be making a new right sided button version object just for Level 13 (or have it be a parameter for which side the button faces)? That way the button will be facing the correct direction and you could still use the invisible barrier to make the player feel like the pressed the button (button on right side for Level 13 and adjust inviso vertical barrier accordingly)? 

If possible too maybe adjust the invisible barrier parameters so it's not just a single invisible line but a box or the outline of the reactor so players can't jump into it anymore and get stuck? (with two vertical sides and a horizontal top). That way the player would never fall into the object again (but does not fix the button on the wrong side issue on level 13).

Maybe do the same for the clock so you cannot jump into it and get stuck too like happens on Level 21 sometimes?

The only other way to "fix" the level 13 reactor issue is to allow transporters facing the same direction for just this level. Then I could just flip the objects around at the bottom of the maze to get the reactor button facing to the left side where the player comes at it from.

Thoughts?

**Comment by jerkyspace** [comment]
Being able to have the button on the right side of a reactor too would also open up new maze design possibilities/eliminate most of the issues with this invisible barrier (that I think is essential to making these objects feel real).

If we go this route then rhe reactor also should not be set off unless you hit the actual button so maybe limit the collision detection accordingly? (+adjust the invisible barrier).

**Comment by jerkyspace** [comment]
Another possible solution on Level 13 is to extend the lower hallway to the left enough so the player can jump over the Reactor and set it off from the left side where the button is (out to just under the yellow key).

For this to work you would have to limit setting the reactor off to the actual button press and expand the invisible barrier to keep the player from going through the reactor or landing inside it (from the right side in this instance).

**Comment by jerkyspace** [comment]
I finally figure out a way to get the reactor on Level 13 facing the way I wanted (button to the left)  without losing the original design idea. It actually expands on that and improves it a bit I think.

Now that I have found a way to mostly avoid the issue in question I think  we need just a little tweaking of the invisible barrier parameters for the Reactor (and Clock) as the were originally.

I still think that if we can we should keep the player from jumping inside both the reactor and clock. Also make the reactor button press more specific to the actual button (smaller hit box than we have now). So you don't set it off by pressing other parts of the reactor other than the button.

.mhc update coming your way this weekend :)

**Comment by jerkyspace** [comment]
Can we restore the reactors to how they were now that I have all of them across the maze collection facing the right way? I miss the invisible barrier and keep running through reactors into walls and force-fields by mistake. It also makes some levels harder like level 18 where you need to turn right around after you run into the reactor to set it off.
