### ISSUE TITLE
Warp Codes coming up as 00 or 000

### ISSUE THREAD

**Issue by jerkyspace** [jessaskey/mhavocpe#60]
Warp codes are being generated as all zero's. Very easy to warp by accident since warp code entry starts at 000.

**Comment by jessaskey** [comment]
Im re-opening this because it just happened with my on my MAME and Im running development v0.58... I understand what is happening a bit more with this now because of the situation. Basically, in MAME, if you have no nvram file saved, it obviously creates one with only 00's in all the memory locations. This is great and all, but the unfortunate side affect of this is that when the data is 'checksummed' to see if it is valid, it passes because the checksum of any number of values of 00 will also be zero. So, when the GAMMA is started, it sees all these zeros and does not recognize that it needs to initialize the EEROM with valid warp codes, so they sit there as zeros and in manifests itself as having a 00 or 000 warp code for all the warps.

Long story a tad longer... Im going to change the EEROM checksumming routine so that the checksums are XOR'ed by a 0xFF value before saving, that way, data checksums of all zeros's will be 0xFF, that means a fresh nvram config file for MAME, will fail the checksumming and the values will all be initialized properly. 

This is fixed in 0.58 but needs 100% testing for sure.
