### ISSUE TITLE
Level 23 maze won't play due to broken Star Castle battle

### ISSUE THREAD

**Issue by jerkyspace** [jessaskey/mhavocpe#65]
Fighters act like they are wall sections that you cannot destroy. You can rack up tons of points but nothing every is destroyed. Walls cannot be destroyed either. Maze does not load even after bonus timer runs out.

**Comment by jessaskey** [comment]
So is this just in the Level Editor right? Because the only way to get to 23 in the 'normal' ROM's is via Transporter from Level 22. I sorta expect some stuff around this because I just assumed that levels 21-24 would work in the editor as stand alone levels but obviously there are some complications.

**Comment by jerkyspace** [comment]
This also still happens in the DEMO romset 0.44 only when you select the level directly form the start of the game.

**Comment by jessaskey** [comment]
Save as the Level 24 issue, you need to start these from Level 21 and play from there.
