### ISSUE TITLE
Doh! Speech FX too repetitive

### ISSUE THREAD

**Issue by jerkyspace** [jessaskey/mhavocpe#72]
The speech FX that plays when you bump your head/hit walls too hard is too repetitive often repeating more times than the actual collision. It's even worse if you get stuck in the gap between the ceiling and a left up or right up wall section.

Suggestion : Limit the times it makes this getting to be really annoying sound all due respect. Maybe only when you hit your head and make sure it never repeats more than once per collision somehow (limit number of times in a specific time space too maybe).

Imagine how often novice players will trigger this sound. All you will hear from the game is a bunch of those sound FX's over and over as it is now.

**Comment by jerkyspace** [comment]
Still an issue 0.47 romset especially when you hit your head or get stuck under Left Down and or Right Down wall sections (hitting the vertical bit). Or hit your head on a wall above a Right Up, Left up or Vertical. 

This triggers multiple "doh" speech loops and goes crazy if the player manages to get stuck in a small gap between walls which is another bug in itself I should list (where a LeftUp, RightUp, Left Down, RightDown or Vertical Wall section is used resulting in a small gap).

It's like it thinks there are more collisions to set off the speech trigger than there actually are or it does not see the extra ones and then turn itself off properly after one speech FX trigger just happened.

Please fix this. Driving me nuts and will make the game look bad at CAX if its stuck going "Doh!Doh!DohDoh!" over and over.

**Comment by jessaskey** [comment]
Okay, this should be removed in the 'final' 0.48 ROMset

**Comment by jessaskey** [comment]
Im curious on this so I reopened it... it seems that Bryan found this bug too where Rex is able to get stuck between a half-wall and the wall above it, then Rex gets stuck in there and just does the head collision sound over and over again. Now that the speech has been removed from the head smashing sound, do things sorta behave better now?

**Comment by jessaskey** [comment]
Im going to put this on the 0.63 milestone and also get in some other sounds for Rex. I think I soved some of the issues I was having with sending speech commands inside the collision routines, so Im hoping I can get this working solidly now.

**Comment by MajorHavoc** [comment]
I would put my speech routine hardware updated in the NMI interrupt routine so that it runs every frame. Do not make it too long though. The main sound routine queues up sounds and the NMI sends them out.  That means I call to start speech is just a call. Runs quickly.  In the collision routines just click a counter for the necessary sound and check those counters in the NMI to start a single sound if that kind. Don’t restart if still running.

**Comment by jessaskey** [comment]
Yeah, it was a weird issue where I forgot that the routine that sends the gamma commands basically ruins all the registers so I was jacking up the Y register in the collision routine which was randomizing the objects that it was comparing too. DOH!!  The RPM version you were using was really almost exactly like the Return of the Jedi version of RPM (which had the support for the TI chip)... so it was pretty easy for me to get the TI speech chip support right into RPM without having to hack it up.  

As an interesting side note (or maybe not that interesting).. both Star Wars and I,Robot used a 6809 CPU for RPM (Slave version for Star Wars and Non-Slave for I,Robot)... I guess Atari must have though that maybe the 6809 was the future CPU because it was no small feat to rewrite RPM completely in 6809 code....  In the end.. the 68000 out did the 6809 for most games from 1984 onwards (outside of the System II) games which used that crazy DEC T-11 CPU (PDP-11).

**Comment by jessaskey** [comment]
Re-instated my old code for this which should work better now that I figured out some stuff. Lets see how it works!
