### ISSUE TITLE
Top Map walls are missing after intra-level Transporter

### ISSUE THREAD

**Issue by jessaskey** [jessaskey/mhavocpe#75]
After the player transports from Level 21 into Level 22, the top map wall are gone. The enemies all seem to be correct however.

**Comment by jerkyspace** [comment]
The red booties and the clock are missing as well but only when you play form 21-22. If you go right to 22 everything is fine.

Also when you select 22 and play through to 23 the red booties are missing on that level too. Again when you go back and select 23 the boots are there.

Finally when you go from selecting 23 to 24 you get stuck in outerspace again even if the bonus timer runs out. Same with selecting the level. 

The boots are probably gone too because the game thinks I still have them from earlier levels so they don't appear in the new one where they are next?

BootsClearOnFlashTransporter?
