### ISSUE TITLE
DEMO mode automatic makes difficulty EASY

### ISSUE THREAD

**Issue by jessaskey** [jessaskey/mhavocpe#82]
When the game is in DEMO mode, it defaults to being set on EASY. I think that in the end, the DEMO mode selection needs to be totally separate from Difficulty so that you can be in DEMO mode at any difficulty level. This is currently an issue because during testing I am releasing games in DEMO mode to make testing easy, however, that is also making the mazes unnaturally easy and we still want difficulty = MEDIUM for testing.

**Comment by jerkyspace** [comment]
All the play-testing and adjustments I have been making were under the assumption we have been working on rom builds at default medium difficulty even in this testing Demo mode. That's what HBMAME says it is set at as well and is what I have been working towards (3 life start/medium diff/extras every 100k/adaptive on/). I keep checking every time before I make speed related adjustments. 

If you have to make a change now and I have to adjust things let's do it sooner than later please. All my maze collections so far are built for factory default medium difficulty and should play that way on an actual machine. We should also turn the outer-space collision detection back on and the gravity pull on ship landings for testing up to CAX in rom builds. You can keep unlimited lives for now and level select but whatever work I do should play correctly on factory default (same enemy speeds, maze timing stuff etc).

Once I get default factory diff dialed in I will check and adjust for easy and hard diff...but to be honest why do we even bother with them? DIp switch settings were all about the operators back in the day and coin play time. Not really an issue nowadays. Players can still make it "easier" with extra lives at 50k, more lives to start, unlimited lives maybe...and make it harder with less extra lives and starting lives....instead of easy, medium (default) and hard settings that will change up how the mazes will play.

I also think actual dip switch select-able Demo Mode for CAX on at least one machine should be select any level with collision detect on in outer-space (plus gravity pull for landings) so we can see how people play/react to all these new levels/changes to get some much needed feedback (and be factory default medium difficulty extras every 100k). 

Thoughts?

**Comment by jerkyspace** [comment]
BTW does the IncrementingVelocity setting in the Editor for Pyroids and other enemies relates to dip switch difficulty level or Adaptive?

**Comment by jessaskey** [comment]
So the difficulty works like this.... 

Easy Value = 00
Medium Value = 01
Hard Value = 02

If 'Incrementing Velocity' is set to True, then every few levels (Im not going to document that here because it depends on warps, how many times a player has died and number of levels completed) the Difficulty increases. So, if  game starts on EASY, then at like level 3, it will 'increment' to 01 (MEDIUM)... and so on.... after like level 7, it actually increments to 02 = HARD. However, it doesn't stop there, it basically can 'increment' up until 5 I think. So when you are in the upper upper levels, you are most likely at the max difficulty of 05. This difficulty affects many things... speed of Reactor Countdown, Timer in Tact Scan, Speed of Maze Enemies.

The complexity of the setting is why it is so difficult to take it out, it would really make the upper levels slow in the end, but as you say, it would at least allow us to manually set everything. Since we are not in an arcade situation anymore, we really are not driven by operator earnings, but my biggest concern at least pre-CAX is that I don't want to touch this topic until after CAX because I feel it will turn into a mess if not done meticulously.

Here is my proposal... Im going to get some stuff fixed this week but for any ROM releases I send out to the testing team, I am going to send out TWO ROM sets... one will be the normal DEBUG versions which put the game in DEMO mode (that will be for folks that can't play through all the levels, aka anyone but Dave)... the other ROM set will be a 'Production' release where it will be NON-DEMO mode which should leave things at MEDIUM difficulty as normal. I will also make sure that the Level Editor version is in NON-DEMO mode and at MEDIUM difficulty if possible.

Does that sound okay for now?  Keep in mind too, that don't spend a ton of time tweaking timing etc... I have a feeling on actual hardware it may be different and once we touch the Adaptive Difficulty it will *definitely* be different.

**Comment by jerkyspace** [comment]
Sounds good to me. Things are already at a good baseline so let's see 
how it all looks at CAX and how other players react.

**Comment by jerkyspace** [comment]
Anyway you can check and verify what difficulty setting the most recent 0.44 "production" NON-DEMO romset is set at? 

There are dip swich already with Bonus Lives and Starting Lives. I just started playing the 0.44 NON-DEMO roms and everything seems too fast as if its actual set to HARD diff this time.

My baseline is comparing where the player is versus the pyroids on the Level 2 maze. Last roms the Pyroids were moving noticebaly slower but this time they are sped up and in the wrong place at the wrong time breaking the "flow pattern" through the level. I am also using a rev 3 no warps TG submission YouTube playback vid I made last year to verify what their speed and location relative to the player "should be" to tell what the diff is set/playing at (or not).

As you noted I don't want to make speed changes and turn this into a mess because of the complexity of the increment velocity stuff and because I am not sure what diff setting I am actually playing on still (so any changes would be even more off).

We really need to lock down a working baseline factory default roms set and working dip switch settings (at least in HBMAME where I am working) so I can at least fix anything that is horribly off before we decide what and how to tweak in more detail later.

3 Lives to Start
100k extra lives
Medium Difficulty

**Comment by jerkyspace** [comment]
It would probably take a while understandably given all the parameters, but being able to playback a level in the editor via HBMAME exactly like it would in the game as far as diff settings and how the adaptive diff/incrementing velocity would actually be/react would be a dream feature if possible.

It also seems like by taking the "operator needs" out of the equation we could reduce the number of things that affect the difficulty complexity and be able to control better how levels especially mazes playback manually without having to guess what all these other parameters will do or not do through lots of back and forth playback.

Again as a player/maze designer all these extra conditions are/were just a headache and that's how all my friends and I felt about AD back in the 80s. I'd prefer a game I could just play one way every time and that's the game speed and difficulty wise whether you warp or not, die too often or not too often, on and on and on. 

It's hard enough already without all this extra difficult clutter that was mostly to please operators, tweak coin count and play time for their needs...not the players.

**Comment by jerkyspace** [comment]
Here is the Rev3 Factory Default playback game I have been using as a reference to see where maze enemies should be in relation to the player and how fast they should be moving versus what we are seeing in these recent rom releases with dip swicth setting issues.

Like DigDug level 1...the maze on Level 2 of Major Havoc was where we could tell if a machine was set to easy, medium or hard settings depending on where the first 4 Pyroids were in relation to the player if you were doing the "pattern" right.

https://youtu.be/33h5A_BT_VU
https://youtu.be/33h5A_BT_VU?t=113

You could move all the way to the right past Pyroid 15 if it was Easy or Medium but if Hard you had to wait a second and then go by it otherwise run right into it moving right without stopping.

Then the pair of Pyroids moving vertically would be out of your way and you could move all the way to the left up the next hallway. If Hard diff they block you and you have to wait.

And so on if you check the video playback versus current romsets....

**Comment by jerkyspace** [comment]
Confirmed.

Current 0.44 romset DEMO-MODE plays as EASY diff still or close to it as I can tell since I have changed the speeds of some things already to try to get it back to MEDIUM DIFF before we found out it was stuck at EASY.
(50k bonus lilves and 9 to start)

Current 0.44 romset NON-DEMO-DEMO plays as HARD diff from what I can tell 
(50k bonus lives and 4 to start)

And in BOTH romsets HBMAME reports that the dip switch settings are "factory default"  despite what actual playback is :
AD ON
Demo Sounds ON
Bonus Life 100k
Difficulty MEDIUM
Lives 3 (2 in Free Play)

Medium Difficulty, 100k extra lives and 3 to start pretty please? (for NON-DEMO MODE roms).

**Comment by jerkyspace** [comment]
So with the 0.45 romsets it appears to be in Medium difficulty....at first...but its still set to bonus lives every 50k even though HBMAME says it is at 100k. 

Everything else seems okay up through Level 5 but then the maze enemies in Level 6 are not moving as fast as they should be according to my "reference" playbacks from Rev 3. 
http://www.youtube.com/watch?v=33h5A_BT_VU&t=8m22s

The TripPads shots are slower at the start. Perkoid23 should be moving faster and at the far right side of the hallway when the player gets past Pyroid32 which is also moving slower. Instead the Perkoid is moving slower and blocks the player from getting up into that hallway if they use the "normal pattern". You can adjust and get by this but I just want to note the anomaly.

This "difficulty offset" also becomes an issue at the start of the Level 9 maze. Under normal medium difficulty conditions you can fall down the first shaft and Perkoid97 is moving away from the player to the right giving them time to hop over it. In this romset when you fall down the same shaft you can easily land right on the Perkoid and die.
http://www.youtube.com/watch?v=33h5A_BT_VU&t=13m55s

Both issues you can work around with different patterns but I am just pointing out there is something that is off with the difficulty. We can live with stuff like this for now and talk more about this at CAX. These things are also easy Editor adjustments outside of tearing apart the difficulty code to find why it's a little off starting at Level 6+.

Besides I am one of the few people that would actually notice these things ;)

I will add to this if I find anything else that is worth bringing up since I am still working through the 0.45 Demo romset first today.
