### ISSUE TITLE
Maze Hint(s) not appearing on Level 22>24

### ISSUE THREAD

**Issue by jerkyspace** [jessaskey/mhavocpe#83]
The text for Maze Hints are appearing in the wrong maze (see below) v1.1.888.0 :

Level 21 
Hint - "WILL AFFECT CLONE REGENERATION"
Hint2 - "MAINFRAME GRAVITY WELL"

Level 22
Hint - "FLASHING TRANSPORTERS ARE ONE WAY"
Hint2 - blank

Level 23
Hint - "SET OFF 4 REACTORS TO DESTROY MAINFRAME"
Hint2 - blank

Level 24
Hint - "ALMOST THERE...KEEP GOING!"
Hint2 - blank

Results 1.1.888.0 =
Level 21 "MAINFRAME GRAVITY WELL WILL AFFECT CLONE REGENERATION"
Level 22 "MAINFRAME GRAVITY WELL"
Level 23 "FLASHING TRANSPORTERS ARE ONE WAY"
Level 24 "SET OFF 4 REACTORS TO DESTROY MAINFRAME"

Hint2 also seems to appear before Hint(1) even though it looks like you switched most Maze Hints to Hint(1) in a recent editor update.

**Comment by jessaskey** [comment]
So, as I dug into this issue, I started getting confused because Im not seeing the Messages that you list above... here is the current list of HINTS for each level.... 

Hint 1 has an 'a' suffix below
Hint 2 has a 'b' suffix below - NOTE: I don't have any B hints for Levels 13-28... 

give me how they should be here in this issue thread and I will get the set up correctly.

Level 13 
mzh30a  .ctext "DODGE ION CANNON SHOTS"

Level 14
mzh31a  .ctext "ION CANNON SUPPORT IS NOT DEADLY"

Level 15
mzh32a  .ctext "TIME JUMPS CAREFULLY"

Level 16 
mzh33a  .ctext "YOU MUST HAVE THE HIGH SCORE BY NOW"

Level 17
mzh40a  .ctext "NO HAND TRICK THIS TIME"

Level 18
mzh41a  .ctext "COLLECT ALL THREE KEYS"

Level 19
mzh42a  .ctext "BOOTIES MASTERY REQUIRED"

Level 20
mzh43a  .ctext "HINT - THE SLOW SHOT IS YOUR BEST SHOT"

Level 21 - Final Station Section 1
mzh50a  .ctext "SET OFF 3 REACTORS TO DESTROY CUBE"

Section 2
mzh51a  .ctext "FLASHING TRANSPORTERS ARE ONE WAY"

Section 3
mzh52a  .ctext "THINGS ARE GETTING OUT OF CONTROL"

Section 4
mzh53a  .ctext "ALMOST THERE...KEEP GOING!"

Level 25 - Secret Level 1
mzh60a  .ctext "LURE MAXOIDS AWAY FROM KEYS"

Level 26 - Secret Level 2
mzh61a  .ctext "BEWARE RAINING IONS"

Level 27 - Secret Level 3
mzh62a  .ctext "TRAP MAXOIDS BEHIND WALLS"

Level 28 - Secret Level 4
mzh63a  .ctext "AVOID ION CANNONS AND COLLECT KEYS"

**Comment by jessaskey** [comment]
Jerky... LMK if this is looking okay now and I will close it...I *think* everything should be in line now with your .mhc file?

**Comment by jerkyspace** [comment]
Now with the 0.45 romset you don't get any Hints after Level 21 when you go through flashing transpos to the next Level 21>22, 22>23 and 23>24.

**Comment by jerkyspace** [comment]
I renamed this to get your attention :)

When we get them back to appearing I can check if they are still out of order or not.

**Comment by jerkyspace** [comment]
Maze hints still not showing on Level 22-24. Not sure why this is closed but needs to be reopened.
