### ISSUE TITLE
HBMAME Bonus Lives and Starting Lives Wrong

### ISSUE THREAD

**Issue by jerkyspace** [jessaskey/mhavocpe#84]
This may be related to the other bug about EASY MODE. 

HBMAME says everything is "factory default" with difficulty medium and extras every 100k and 3 lives to start (under dip switch settings). 

But, game attract mode stills says extras every 50k with 4 lives to start and plays that way in game in NON-DEMO mode 0.44 romset. Will check DEMO MODE roms later today/this weekend and report if same.

I tried changing dip switch settings manually several times...reset game....and it is still stuck in extras every 50k and 4 lives mode (possibly EASY difficulty as well) despite what HBAME says under dip switch settings.

**Comment by jessaskey** [comment]
There is an explanation for all this but I don't think I have ever given it to you so... hopefully this makes a little more sense after you read this.

So, in the original havoc game, it was 'old school' in that you set the dips and then you played the game and it was like the dips said. Havoc was one of the last games like that because in games after this, they no longer had dip switches, you just adjusted the settings of the game via Self Test. They did this because the DIP switches were a PITA to dig into the cabinet etc and switch. In MAME, this is fine tho, because changing the DIPS is as easy as hitting TAB. In mhavocpe, I moved the Settings into Self Test like other games, so essentially the DIPS don't really tell you anything. Since they are there, they should represent the 'fallback default' settings, but if you go into Self Test (F2) and hit the Aux Coin (F1) a few times then you will come across the 'Settings' screen. There you can scroll through the settings and change them. 

HOWEVER!!!  There is currently a bug in there that shows things funky, but you can at least still switch things and then see how they are actually in the game (attract mode tells you correctly the extra lives and coin settings)... I will verify the Difficulty tonight and get this fixed in tonights ROMs.

This is why tho that changing the DIPS has no effect. The only way to get the DIP values is to use the setting 'Load Default Values' in Self Test... that will take what you have in the DIPS and use them.

Make sense?

More to come....

**Comment by jerkyspace** [comment]
Dip switch settings for these now working via Self Test mode settings.
