### ISSUE TITLE
Objects outside maze still visible on Level 21-23

### ISSUE THREAD

**Issue by jerkyspace** [jessaskey/mhavocpe#90]
You can still see the "hidden" extra Reactoids on the map blinking on Level 21-23 . The location I choose also is right on top of part of the scoring screen text. I can move it to avoid that but making them all "invisible" would be best is possible.

There also looks to be a pair of phantom Perkoids or other enemies that appear near the bottom left of Level 21 and then are at the top of Level 22-24. Some other enemy objects join them around level 22/23 and then stop moving.

**Comment by jerkyspace** [comment]
Some of these objects come from broken TripPads on level 22 and 23 it seems.
https://github.com/jessaskey/mhavocpe/issues/91

**Comment by jerkyspace** [comment]
This also may be fixed if my adjustment that go the TripPads working again on Level 22-24 take sin the romsets. Don't close until we see for sure but working now in Editor HBMAME (fixed trips pads = no extra objects where they don't belong).

**Comment by jessaskey** [comment]
Okay, so for objects showing on screen that are not supposed to, Im going to do a position hack so that you can put them into a specific location and they will be skipped for drawing. The objects that will need to work this way are..

Level 21 (Section 1)

- Reactor

Level 22 (Section 2)

- Reactor
- Red Key
- Red Door

Level 23 (Section 3)

- Reactor
- Red Key
- Red Door

Im going to try this... for those objects, simply make sure that they have an X position that has the High Byte = $00... Example... On Level 22, here the reactor and key are down in the correct position.

![image](https://user-images.githubusercontent.com/3683098/64127794-6ff6fe80-cd70-11e9-9770-77b1e988dc58.png)


This is what the position looks like in the editor..  Key first..

![image](https://user-images.githubusercontent.com/3683098/64127820-9321ae00-cd70-11e9-8900-e66b44d9ae8b.png)

And Reactor..

![image](https://user-images.githubusercontent.com/3683098/64127844-ab91c880-cd70-11e9-9876-5aeb71c0f375.png)
